[package]
name = "gitrs"
version = "0.1.3"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
syntect = "5.2.0"
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0.12"
regex = "1.11.1"
